/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet; 
import java.sql.SQLException;
import java.util.ArrayList; 
import java.util.Date;
import java.util.List;
import java.util.logging.Level; 
import java.util.logging.Logger;
import javax.swing.JButton; 
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField; 
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel; 
import pack.control.c_koneksi; 
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author Dayinta-PC
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();
    String nol_jam="";
    String nol_menit="";
    String nol_detik="";

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko(this);
        ctoko.isiTable();
        setTanggal();
        setJam();
        String user = null;
        admin.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbltanggal = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cbKategori = new javax.swing.JComboBox<>();
        panel1 = new java.awt.Panel();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        cbCari = new javax.swing.JComboBox<>();
        cari = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel2.setText("AdminToko");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 18);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel4.setText("Data Barang Di Toko");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 20, 230, 40);

        admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(admin);
        admin.setBounds(110, 10, 110, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        lbltanggal.setBackground(new java.awt.Color(255, 255, 255));
        lbltanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lbltanggal);
        lbltanggal.setBounds(490, 10, 100, 30);

        lblJam.setBackground(new java.awt.Color(255, 255, 255));
        lblJam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lblJam);
        lblJam.setBounds(610, 10, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel6.setText("Kategori Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 170, 120, 18);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel3.setText("Kode Barang");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 90, 120, 18);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel5.setText("Nama Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 130, 120, 18);

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel7.setText("Jenis Packaging");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 210, 120, 18);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel8.setText("Harga");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 250, 120, 18);

        harga.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel2.add(harga);
        harga.setBounds(170, 250, 300, 24);

        kode.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel2.add(kode);
        kode.setBounds(170, 90, 300, 24);

        nama.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jPanel2.add(nama);
        nama.setBounds(170, 130, 300, 24);

        cbJenis.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack" }));
        jPanel2.add(cbJenis);
        cbJenis.setBounds(170, 210, 300, 24);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        cbKategori.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Barang Lain" }));
        jPanel3.add(cbKategori);
        cbKategori.setBounds(160, 90, 300, 24);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 80, 560, 220);

        panel1.setBackground(new java.awt.Color(204, 204, 255));
        panel1.setLayout(null);

        edit.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        panel1.add(edit);
        edit.setBounds(20, 110, 100, 27);

        clear.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        panel1.add(clear);
        clear.setBounds(20, 190, 100, 27);

        delete.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        panel1.add(delete);
        delete.setBounds(20, 270, 100, 27);

        logout.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        panel1.add(logout);
        logout.setBounds(20, 350, 100, 27);

        save.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        panel1.add(save);
        save.setBounds(20, 40, 100, 27);

        jPanel2.add(panel1);
        panel1.setBounds(580, 80, 140, 420);

        jComboBox3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Makanan--" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(170, 170, 300, 24);

        cbCari.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Makanan--" }));
        jPanel2.add(cbCari);
        cbCari.setBounds(320, 320, 140, 24);

        cari.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel2.add(cari);
        cari.setBounds(470, 320, 90, 27);

        panel2.setBackground(new java.awt.Color(204, 204, 255));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode_Barang", "Nama_Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        panel2.add(jScrollPane1);

        jPanel2.add(panel2);
        panel2.setBounds(10, 360, 560, 140);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel1.setText("Pencarian Berdasarkan Kategori Makanan");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 10, 300, 18);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 310, 560, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 730, 510);

        setSize(new java.awt.Dimension(746, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        ctoko.Reset();
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        ctoko.CariKategori();
        ctoko.isiTable();
    }//GEN-LAST:event_cariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String Halouser = login.useraktif;
        admin.setText(Halouser);
    }//GEN-LAST:event_formWindowOpened

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1){
        kode.setText(tblData.getValueAt(baris, 0).toString());
        nama.setText((String) tblData.getValueAt(baris, 1));
        cbKategori.setSelectedItem(tblData.getValueAt(baris, 2).toString());
        cbJenis.setSelectedItem(tblData.getValueAt(baris, 3).toString());
        harga.setText(tblData.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField harga;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nama;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JButton save;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    
    public JTextField getTxtKode() {
        //To change body of generated methods, choose Tools | Templates.
         return kode;
    }

    public JTextField getTxtNama() {
        //To change body of generated methods, choose Tools | Templates.
         return nama;
    }

    public JTextField getTxtHarga() {
        //To change body of generated methods, choose Tools | Templates.
         return harga;
    }

    public JComboBox getCbKategori() {
        //To change body of generated methods, choose Tools | Templates.
         return cbKategori;
    }

    public JComboBox getCbJenis() {
        //To change body of generated methods, choose Tools | Templates.
         return cbJenis;
    }
    
    public JComboBox getCbCariKategori(){  
        return cbCari;    
    }   
     
    public JButton getButtonHapus(){   
        return delete;   
    }   
    
    public JButton getButtonBersih(){  
        return clear;  
    }   
    
    public JButton getButtonSimpan(){ 
        return save;   
    }  
    
    public JButton getButtonUbah(){  
        return edit; 
    }    
    
    public JButton getButtonKeluar(){     
        return logout;  
    }  
    
    public JTable getTableData(){     
        return tblData;  
    }
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        lbltanggal.setText(kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if(nilai_jam<= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                lblJam.setText("Jam : "+ jam + ":" + menit + ":" + detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
}
